// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
  apiKey: "AIzaSyC0egVMdjMeh3tolBwlkIQJb_RSsd99Zs4",
  authDomain: "water-quality-43dbd.firebaseapp.com",
  projectId: "water-quality-43dbd",
  storageBucket: "water-quality-43dbd.appspot.com",
  messagingSenderId: "697483963078",
  appId: "1:697483963078:web:519bbb9046f601a1dc85c7",
  measurementId: "G-CWS8WV21DK"

  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyC0egVMdjMeh3tolBwlkIQJb_RSsd99Zs4",
  authDomain: "water-quality-43dbd.firebaseapp.com",
  projectId: "water-quality-43dbd",
  storageBucket: "water-quality-43dbd.appspot.com",
  messagingSenderId: "697483963078",
  appId: "1:697483963078:web:519bbb9046f601a1dc85c7",
  measurementId: "G-CWS8WV21DK"
  );

}
